### PR TITLE
#465 - fix faulty test

### LINKED ISSUE #465: Proofs and Docker build are failing in Artipie due to faulty test
There is test that id failing in proofs and Docker build workflows, it should be fixed.

Here is message from logs:
```
2020-08-19T14:34:08.3482026Z [INFO] Results:
2020-08-19T14:34:08.3482187Z [INFO] 
2020-08-19T14:34:08.3482313Z [ERROR] Failures: 
2020-08-19T14:34:08.3505222Z [ERROR]   HealthSliceTest.returnsBadRequestForBrokenStorage:68 
2020-08-19T14:34:08.3505701Z Expected: response: (<UNAVAILABLE> and [<91>, <123>, <34>, <115>, <116>, <111>, <114>, <97>, <103>, <101>, <34>, <58>, <34>, <102>, <97>, <105>, <108>, <117>, <114>, <101>, <34>, <125>, <93>])
2020-08-19T14:34:08.3506799Z      but: response was: <(StatefulResponse: state=(StatefulConnection: status=OK, headers=["content-type": "application/json; charset=UTF-8", "content-length": "18"], body=[91, 123, 34, 115, 116, 111, 114, 97, 103, 101, 34, 58, 34, 111, 107, 34, 125, 93]))>
2020-08-19T14:34:08.3507102Z [INFO] 
2020-08-19T14:34:08.3507233Z [ERROR] Tests run: 109, Failures: 1, Errors: 0, Skipped: 4
```

### PR DESCRIPTION
**Pull request by genryxy**
Closes #465 
Replace param of constructor `/` with `null`.

### CODE REVIEW

File: src/test/java/com/artipie/http/HealthSliceTest.java [hunk 1]
```diff
@@ -66,7 +64,7 @@ void returnsOkForValidStorage() {
     @Test
     void returnsBadRequestForBrokenStorage() {
         MatcherAssert.assertThat(
-            new HealthSlice(new Settings.Fake(new FileStorage(Paths.get("/")))),
+            new HealthSlice(new Settings.Fake(new FileStorage(null))),
```
Comment (olegmoz) [inline src/test/java/com/artipie/http/HealthSliceTest.java:67]: @genryxy that's a smart fix, but in Artipie project we are trying to avoid using `null` values.

Could you please implement `Storage` interface with all methods throwing exception? It's going to be more verbose, but will make intent more obvious. Using shortcuts is what brought us the problem in the first place.

**Review by olegmoz — CHANGES_REQUESTED** [review]
@genryxy thanks, please see the comment

**Comment by genryxy** [comment]
@olegmoz thanks, added implementation of the fake storage

File: src/main/java/com/artipie/http/HealthSlice.java [hunk 2]
```diff
@@ -93,7 +94,7 @@ public Response response(final String line,
                 new Key.From(".system", "test"),
                 new Content.From("OK".getBytes(StandardCharsets.US_ASCII))
             ).thenApply(none -> true).exceptionally(ignore -> false);
-        } catch (final IOException ignore) {
+        } catch (final IOException | UncheckedIOException ignore) {
```
Comment (olegmoz) [inline src/main/java/com/artipie/http/HealthSlice.java:97]: @genryxy handling `UncheckedIOException` here is wrong. It covers only one special case, the `FakeStorage` you have introduced in this PR. You should catch `Exception` here, handling just `IOException` here was wrong.

**Review by olegmoz — CHANGES_REQUESTED** [review]
@genryxy thank you, please see one comment

**Comment by genryxy** [comment]
@olegmoz changed, please take a look

**Review by olegmoz — APPROVED** [review]
@genryxy thanks

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#471` is not assigned, can't get performer
