### PR TITLE
#633 - Response 404 to request not related to repos

### LINKED ISSUE #633: Respond with 404 to request not related to repositories
`SliceByPath` should not crash, but respond with `404` for requests that cannot be directed to a repository, such as `/favicon.ico` or `robots.txt` for example

### PR DESCRIPTION
**Pull request by genryxy**
Closes #633 
Respond with 404 to request not related to repositories in `SliceByPath`

### CODE REVIEW

File: src/main/java/com/artipie/http/SliceByPath.java [hunk 1]
```diff
@@ -76,18 +76,13 @@ public Response response(final String line, final Iterable<Map.Entry<String, Str
...
-                    throw new IllegalStateException("Expected at least 2 path segments");
-                }
-                key = new Key.From(split[0], split[1]);
-            } else {
-                if (split.length < 1) {
-                    throw new IllegalStateException("Expected at least 1 path segment");
-                }
-                key = new Key.From(split[0]);
+            key = this.keyFromPath(new RequestLineFrom(line).uri().getPath());
+            if (key.equals(Key.ROOT)) {
```
Comment (olegmoz) [inline src/main/java/com/artipie/http/SliceByPath.java:80]: @genryxy I see that you use `Key.ROOT` as special value that means repository name cannot be extracted from path. That is not that great design to have such values with special handling. It will be more obvious to return `Optional<Key>` from method and have special handling for absent value

File: src/main/java/com/artipie/http/SliceByPath.java [hunk 2]
```diff
@@ -98,4 +93,25 @@ public Response response(final String line, final Iterable<Map.Entry<String, Str
...
+        if (this.settings.layout().equals("org")) {
+            if (split.length >= 2) {
+                key = new Key.From(split[0], split[1]);
+            }
+        } else {
+            if (split.length >= 1) {
+                key = new Key.From(split[0]);
+            }
+        }
+        return key;
```
Comment (olegmoz) [inline src/main/java/com/artipie/http/SliceByPath.java:115]: @genryxy using not `final` variables should be avoided. Mutable values make code harder to understand. Please change `key` variable to be `final`.

**Review by olegmoz — CHANGES_REQUESTED** [review]
@genryxy thanks, please see two comments

**Review by olegmoz — APPROVED** [review]
@genryxy thanks, merging

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#686` is not assigned, can't get performer
